#dist: trusty
dist: xenial
sudo: required
language: cpp
compiler: gcc

#before_install:
#    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#    - sudo apt-get update -qq

#install:
#   - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev
#   - sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev
#   - sudo apt-get install libtinyxml2-dev zlib1g-dev libb64-dev

matrix:
    include:
        - os: linux
          env: CONFIG=Release Toolchain=
          install: sudo apt-get install libtinyxml2-dev zlib1g-dev libb64-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev
          
        - os: linux
          env: CONFIG=Release Toolchain=../cmake/linux32-toolchain.cmake
          install: 
            - sudo apt-get install libglib2.0-dev:i386
            - sudo apt-get install libpulse-dev:i386
            - sudo apt-get install gcc-multilib g++-multilib zlib1g-dev:i386 libb64-dev:i386 libtinyxml2-dev:i386 libsdl2-dev:i386 libsdl2-image-dev:i386 libsdl2-mixer-dev:i386 libsdl2-ttf-dev:i386
script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_TOOLCHAIN_FILE="${Toolchain}" ..
    - make
