dist: trusty
sudo: required
language: cpp
compiler: gcc

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
# Install newest g++
    - sudo apt-get install -qq g++-7
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
# Install SDL 2.0
    - sudo apt-get install libsdl2-dev
    - sudo apt-get install libsdl2-image-dev
    - sudo apt-get install libsdl2-ttf-dev
    - sudo apt-get install libsdl2-mixer-dev

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
