#dist: trusty
dist: xenial
sudo: required
language: cpp
compiler: gcc

before_install:
#    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#    - sudo apt-get update -qq

install:
# Install g++ 5 for c++14
#    - sudo apt-get install g++-5
#    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
# Install SDL 2.0
    - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev
    - sudo apt-get install libsdl2-dev
    - sudo apt-get install libsdl2-image-dev
    - sudo apt-get install libsdl2-ttf-dev
    - sudo apt-get install libsdl2-mixer-dev
# Install tinyxml2
    - sudo apt-get install libtinyxml2-dev
# Install ZLIB
    - sudo apt-get install zlib1g-dev
# Install Libb64
    - sudo apt-get install libb64-dev
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
