dist: jammy
sudo: required
language: cpp
compiler: gcc
env:
- CONFIG=Release PLATFORM=linux   BIT=64
- CONFIG=Release PLATFORM=linux   BIT=32
- CONFIG=Release PLATFORM=windows BIT=64
- CONFIG=Release PLATFORM=windows BIT=32

- CONFIG=Debug PLATFORM=linux   BIT=64
- CONFIG=Debug PLATFORM=linux   BIT=32
- CONFIG=Debug PLATFORM=windows BIT=64
- CONFIG=Debug PLATFORM=windows BIT=32
install:
- sudo apt-get update
- sudo ./scripts/fetch_dev_dependencies.sh
script:
- ./scripts/compile.sh
before_deploy:
- ./scripts/pack_artifacts.sh
deploy:
  provider: releases
  skip_cleanup: true
#  draft: true
  file_glob: true
  prerelease: true
  on:
      tags: true
      condition: $CONFIG = Release
      branch: master
      repo: AgoutiGames/RawSalmonEngine
  api_key:
    secure: RN+Wgtl5VulBoFqwwjnJQ49CImrqNBYLmxcAaPjguTA+wsuAgGGyt8z84fl8D0mdU2ZxFRGrAQkXI9i9RjLi8uU/EA/yUEBW2f3A4Q/haQHplo9OyCC2roBOdz5I/zYtlKmAunX0NG6Mpu/vnyQbAqcndYhS+Wz3HVmZQ2xmH70i3Rj/l+p9MA/KzH2AM8kR18sBkpL6tbkNx+WVGhDFLNrR6VBDl8DGTOGBsrQYfxlu2064EZv16qa2HrwAFdE+5QUaY5ESsScCIbkaz5/XwIoR6hNLSN2ltmoUOruSvqL8iP/B/mJD3xIdRH9hwEhXL3PkJG3xScorfGYFwhW48+Vt5br0Writ5QOJpPtkz57KPoC6R6rSM8g6K7LLcvt+DXnRcSCjC9JkwlBRsEe70zBrT11nTe0SdBZitwsc3qPxJrox2LHf0PEqcC2qypNuSG6CdTXVbGqnDE+0MGsurLKNcF142Md8cknFC4DplYgKsIk+u49s2DGhAkigeALyWr326Cg2VdhO2aFaSLAL012BlnaUuHscWDx66/DHbTkg4U2NEKOpwB/JLw70GDNarjyrWrD/FQtmquGITxtSi/cQkxsRK781q9FYb+9UpK+OZpO9yTD/BlEqt2wGeNbS7QqTtdM0Zb3pFpJjjRqwy8Ufsbgx4fvzBQHFKuViIzM=
  file: RawSalmon*
