dist: trusty
sudo: false

language: cpp

compiler: gcc

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7
        - cmake
        - libsdl2-dev
        - libsdl2-image-dev
        - libsdl2-ttf-dev
        - libsdl2-mixer-dev

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
